import { createBotCheat } from "./cheat.js";


// createBotCheat("0dP77Uq565");
// createBotCheat("_75XA_pQ");
// createBotCheat("9_v_F_7_A__");
// createBotCheat("f8j3h2X___q");
// createBotCheat("23TN_8_RfI4");
// createBotCheat("vZpde_Qbl_9");
// createBotCheat("J_5_2N");
// createBotCheat("7__4U_");
// createBotCheat("6_63_7G_6");
// createBotCheat("e_41__i");
// 10
// createBotCheat("4__r75zU");
// createBotCheat("XV6r_2_4_");
// createBotCheat("__9_J0_");
// createBotCheat("4B32JK5");
// createBotCheat("_44_8oWc_");
// createBotCheat("43d2ev");
// createBotCheat("lT_5Fl_0_5");
// createBotCheat("_f_X9_O");
// createBotCheat("NF5____");
// createBotCheat("__y_j_");
// 20
// createBotCheat("_a____Z_76j");
// createBotCheat("89QO784");
// createBotCheat("_1f___YZ_");
// createBotCheat("e7DW_9_P91");
// createBotCheat("t_K77__A__m");
// createBotCheat("_Q__9_h3i00");
// createBotCheat("__7_LeV9");
// createBotCheat("_37_3g");
// createBotCheat("_A_eX_n");
// createBotCheat("C_____03");
// 30
// createBotCheat("__Q_R_5_36F");
// createBotCheat("w_H_3p_");
// createBotCheat("j19_4___2Vk");
// createBotCheat("56_le__58_");
// createBotCheat("B__8_c_2");
// createBotCheat("0E2T7s282__");
// createBotCheat("6F2j5__Q6_");
// createBotCheat("z_xY____4");
// createBotCheat("p_3_7W_");
// createBotCheat("_4e8_46__");
// 40
// NEW
// createBotCheat("_4B_q7VV_7w");
// createBotCheat("_F_Ri_7_0_");
// createBotCheat("2486m7_0__");
// createBotCheat("0_CSo_4H__p");
// createBotCheat("Is0s_8z");
// createBotCheat("uDG906___Ho");
// createBotCheat("6___l__87");
// createBotCheat("7_f6__9SI");
// createBotCheat("518__834__G");
// createBotCheat("__8e____u");
// 50
// createBotCheat("7s3Tw_4__");
// createBotCheat("v_4u_f");
// createBotCheat("_49W__p__");
// createBotCheat("9Q___1");
// createBotCheat("_j_S_H");
// createBotCheat("_V97hf_");
// createBotCheat("__up6_");
// createBotCheat("0_15_J__");
// createBotCheat("__5_X_DB1");
// createBotCheat("0464__");
// 60
// createBotCheat("__O__o");
// createBotCheat("0_2_6WE9nUT");
// createBotCheat("5_3_1_7__F");
// createBotCheat("406o92__");
// createBotCheat("_92_p_");
// createBotCheat("82H_0__r_");
// createBotCheat("____7u");
// createBotCheat("27__5_FZ0f_");
// createBotCheat("2y____7W8");
// createBotCheat("7_q_P51_");
// 70
// createBotCheat("jn5_Vc_0");
// createBotCheat("_779_z_0h0");
// createBotCheat("H_H82T__3_");
// createBotCheat("_5_K_kY_69");
// createBotCheat("U9ay6fw___3");
// createBotCheat("___iwy2C_W");
// createBotCheat("__by8_Yo");
// createBotCheat("7_8__D34_");
// createBotCheat("7_3_Qd3");
// createBotCheat("J_3LIv_");
// 80
// createBotCheat("QOw9749y_");
// createBotCheat("_07_i6");
// createBotCheat("c_G5_H6ow");
// createBotCheat("_4Jc2_2");
// createBotCheat("2V_91H__");
// createBotCheat("yn9L_tt");
// createBotCheat("L29hw_5");
// createBotCheat("LE9f6qG_");
// createBotCheat("_H_u906c");
// createBotCheat("_fh54__X");
// 90
// createBotCheat("__y__0_");
// createBotCheat("8_t935_");
// createBotCheat("__35V_64d");
// createBotCheat("2l__6KM_OD");
// createBotCheat("r8z0____3");
// createBotCheat("___m_5q_1");
// createBotCheat("9__99_wP_");
// createBotCheat("1___iV_if3");
// createBotCheat("_Tq87Ek9");
// createBotCheat("9f7a308_165");
// 100
// createBotCheat("rN6t862_gp");
// createBotCheat("As1P_u_8R");
// createBotCheat("Ph_3EMA");
// createBotCheat("72____7__");
// createBotCheat("B5____bK_");
// createBotCheat("48_d__7_1_8");
// createBotCheat("_w9g_3_8");
// createBotCheat("Ki1R8R4_");
// createBotCheat("D_3_4J___A");
// createBotCheat("_HG1kl");
// 110
// createBotCheat("_c650__5_");
// createBotCheat("_t_LWZt_WN");
// createBotCheat("M__r__1");
// createBotCheat("_pDQn9C");
// createBotCheat("_x_O7lF");
// createBotCheat("_b_6AN9");
// createBotCheat("_N0_0_0__");
// createBotCheat("xCd_0____3");
// createBotCheat("7W_O4_");
// createBotCheat("7__4_8");
// 120
// createBotCheat("5G_2405776T");
// createBotCheat("fQ_Y__");
// createBotCheat("os_Rr4");
// createBotCheat("q0_H__5F__");
// createBotCheat("sL__t773i_");
// createBotCheat("__5_Q7_58E_");
// createBotCheat("_O29_Rpu7");
// createBotCheat("0b___L6CV");
// createBotCheat("05_____m8");
// createBotCheat("1w_Ln4_56_");
// 130
